
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R		 
sudo: required
cache: 
  - packages	
  - /usr/local
dist: trusty

r_github_packages:
  - jimhester/covr
    
before_install:
    # install most recent QGIS
    #- sudo sh -c 'echo "deb http://qgis.org/ubuntugis-ltr trusty main" >> /etc/apt/sources.list'  
    #- sudo sh -c 'echo "deb-src http://qgis.org/ubuntugis-ltr trusty main" >> /etc/apt/sources.list'
    #- sudo sh -c 'echo "deb http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu trusty main" >> /etc/apt/sources.list'
    #- wget -O - http://qgis.org/downloads/qgis-2016.gpg.key | gpg --import
    #- gpg --fingerprint 073D307A618E5811
    #- gpg --export --armor 073D307A618E5811 | sudo apt-key add -
    
    #- sudo apt-get autoremove
    #- sudo apt-get autoclean
    #- sudo apt-get -f install
    #- sudo apt-get autoremove qgis
    #- sudo apt-get --purge remove qgis
    
    # - sudo apt-get install grass
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
    - sudo apt-get update
    - sudo apt-get install qgis python-qgis qgis-plugin-grass grass gdal libproj-dev
    
    # related to "cannot connect to X Server" error : http://askubuntu.com/questions/175611/cannot-connect-to-x-server-when-running-app-with-sudo
    #- xhost local:root
    #- sudo DISPLAY=$DISPLAY gedit /etc/profile
    # - sudo sh -c 'echo Defaults env_keep="DISPLAY XAUTHORITY" >> ~/visudo' 

# imitate a X virtual display -> https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  
notifications:
  email:
    on_success: change
    on_failure: change
  slack:
      rooms:
        - giscience-fsu:3GsmuFR1hkVOUHOPwdra8NXG#rqgis
      rooms:
        - giscience-fsu:3GsmuFR1hkVOUHOPwdra8NXG#rqgis
    
after_success:
  - Rscript -e 'covr::codecov()'

# inspect log of failing tests
after_failure: "cat /home/travis/build/jannes-m/RQGIS/RQGIS.Rcheck/00check.log"