# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r		 
cache: packages	

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
      - sourceline: 'deb http://qgis.org/ubuntugis-ltr trusty main'
        key_url: 'http://qgis.org/downloads/qgis-2017.gpg.key'
    packages:
      - libgdal-dev
      - libudunits2-dev
      - python-gdal
      - saga
      - equivs

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      latex: false
      env: linux
      install: R -q -e 'tic::install()'
      after_install: R -q -e 'tic::after_install()'
      script: R -q -e 'tic::script()'
      before_deploy: R -q -e 'tic::before_deploy()'
      deploy:
          provider: script
          script: R -q -e 'tic::deploy()'
          on:
            branches: master
            condition:
               - $TRAVIS_PULL_REQUEST = false
               - $TRAVIS_EVENT_TYPE != cron
      after_deploy: R -q -e 'tic::after_deploy()'
      after_script: R -q -e 'tic::after_script()'
      after_success: R -q -e 'tic::after_success()'

    ### build QGIS DEV on macOS
    - os: osx
      latex: false
      sudo: false
      env: mac
      install: R -q -e 'tic::install()'
      after_install: R -q -e 'tic::after_install()'
      script: R -q -e 'tic::script()'

# if we install everything from ubuntugis-unstable PPA, we get GDAL2 but only QGIS 2.14.X for trusty
# if we install everything from qgis.org/ubuntugis-ltr, we get most recent QGIS but missing GDAL2

before_install:
  # we need to fake gdal-abi-2-1-3 as qgis won't find it otherwise because it searches for gdal20
  # see https://gis.stackexchange.com/questions/216780/cannot-install-qgis-2-18-from-repository-on-debian-stretch-package-gdal-abi-2
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then chmod ugo+x inst/travis/gdal-abi.sh; fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then ./inst/travis/gdal-abi.sh; fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sudo equivs-build gdal-abi.control && sudo sudo dpkg -i gdal-abi-2-1-0_2.1.0_all.deb && sudo rm -rf gdal-abi-2-1-0_2.1.0_all.deb && sudo rm -rf gdal-abi.control; fi
    
  # install latest qgis-ltr using aptitude to resolve dependencies
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then sudo aptitude install -y qgis python-qgis; fi  
  
  #############
  # OSX
  #############
  
  # tap osgeo4mac tap
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew tap osgeo/osgeo4mac; fi
   
  # install saga-gis-lts
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install saga-gis-lts && brew link saga-gis-lts --force; fi
  
  # we need python2
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install python@2; fi
  # install required python packages
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then pip2 install --user psycopg2 future matplotlib pyparsing gdal pyyaml jinja2 owslib pygments; fi
  
    # Solve gfortran conflict
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then sudo rm -rf /usr/local/gfortran/bin/gfortran && sudo rm /usr/local/include/c++; fi
  # install grass7 and unlink it so that the QGIS linking later on works
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install grass7 && brew unlink grass7; fi
  # install qgis2
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install qgis2; fi
  
  
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew link --overwrite --force gdal2; fi
  - R -q -e 'install.packages("remotes"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'
  
# imitate a X virtual display -> https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - "export DISPLAY=:99.0"
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sh -e /etc/init.d/xvfb start; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )& fi
  - sleep 3 # give xvfb some time to start
  
notifications:
  slack:
      rooms:
        - giscience-fsu:3GsmuFR1hkVOUHOPwdra8NXG #rqgis
  on_success: change # default: always
  on_failure: change # default: always
  email: false
